im:
  c2s:
    tcp:
      port: 1024
    websocket:
      port: 2048
      
      
c2s:
  zookeeper:
   url: 114.55.255.143:2181
  path: /easy-im/server
  server: true
  port: 8888
  

dubbo:
  timeOut: 3000
  address: 114.55.255.143:2181