sr2f:
  zookeeper:
   url: 114.55.255.143:2181
  path: /easy-im/server
  client: true
  
mybatis:
    type-aliases-package: com.wl.easyim.biz.domain
    configuration:
        map-underscore-to-camel-case: true
        default-fetch-size: 100
        default-statement-timeout: 30